name: BuildAndRunStuff

on:
  pull_request:
  push:
    branches: [ 'main', 'beta' ]

  workflow_dispatch:
    inputs:
      extra_flags:
        description: "Extra flags to pass to bazel"
        default: ''
        required: false

jobs:
  build-with-bazel:
    name: ${{matrix.cfg.name}}

    runs-on: ${{matrix.cfg.os}}

    strategy:
      matrix:
        cfg:
          - { name: 'Linux Intel GCC',            output: 'linux_gcc_libstdcxx',          os: 'ubuntu-24.04',     cc: 'gcc',    cxx: 'g++',     flags: }
          - { name: 'Linux Intel LLVM/libstdc++', output: 'linux_llvm_libstdcxx',         os: 'ubuntu-24.04',     cc: 'clang',  cxx: 'clang++', flags: }
          - { name: 'Linux Intel LLVM/libc++',    output: 'linux_llvm_libcxx',            os: 'ubuntu-24.04',     cc: 'clang',  cxx: 'clang++', flags: '--config=libc++' }
          - { name: 'Linux Arm64 LLVM/libc++',    output: 'linux_llvm_libcxx',            os: 'ubuntu-24.04-arm', cc: 'clang',  cxx: 'clang++', flags: '--config=libc++' }
          - { name: 'MacOS Intel GCC',            output: 'macos_x86-64_gcc_libstdcxx',   os: 'macos-15-intel',   cc: 'gcc-15', cxx: 'g++-15',  flags: }
          - { name: 'MacOS Intel LLVM/libc++',    output: 'macos_x86-64_llvm_libcxx',     os: 'macos-15-intel',   cc: 'clang',  cxx: 'clang++', flags: }
          - { name: 'MacOS Arm64 GCC',            output: 'macos_aarch64_gcc_libstdcxx',  os: 'macos-15',         cc: 'gcc-15', cxx: 'g++-15',  flags: }
          - { name: 'MacOS Arm64 LLVM/libc++',    output: 'macos_aarch64_llvm_libcxx',    os: 'macos-15',         cc: 'clang',  cxx: 'clang++', flags: }

    env:
      CC: ${{matrix.cfg.cc}}
      CXX: ${{matrix.cfg.cxx}}

    steps:
      - name: check out repository
        uses: actions/checkout@v2

      - name: install infrastructure (Linux)
        if: contains(matrix.cfg.os, 'ubuntu-24.04')
        run: |
          sudo apt-get install libc++-dev libc++abi-dev
          sudo ln -s /usr/lib/llvm-18/include/c++/v1 /usr/include/c++/v1

      - name: build
        run: bazel build                     --show_result=100 -c opt --dynamic_mode=off ${{matrix.cfg.flags}} ${{github.event.inputs.extra_flags}} //...

      - name: test
        run: bazel test --test_output=errors --show_result=100 -c opt --dynamic_mode=off ${{matrix.cfg.flags}} ${{github.event.inputs.extra_flags}} //...

      - name: run (Linux)
        if: matrix.cfg.os == 'ubuntu-24.04'
        run: |
          file bazel-bin/sandbox/dso_loader bazel-bin/sandbox/dso_demo.so
          ldd bazel-bin/sandbox/show_args bazel-bin/sandbox/dso_loader bazel-bin/sandbox/dso_test bazel-bin/sandbox/dso_demo.so
          bazel-bin/sandbox/show_args foo bar quz
          bazel-bin/sandbox/dso_loader bazel-bin/sandbox/dso_demo.so

      - name: run (MacOS)
        if: contains(matrix.cfg.os, 'macos-15')
        run: |
          file bazel-bin/sandbox/dso_loader bazel-bin/sandbox/dso_demo.so
          otool -L -H bazel-bin/sandbox/show_args bazel-bin/sandbox/dso_loader bazel-bin/sandbox/dso_test bazel-bin/sandbox/dso_demo.so
          bazel-bin/sandbox/show_args foo bar quz
          bazel-bin/sandbox/dso_loader bazel-bin/sandbox/dso_demo.so

      - name: make tarball
        run: tar cf output-${{matrix.cfg.output}}.tar -C bazel-bin/sandbox dso_demo.so dso_loader dso_test show_args

      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build_outputs.zip
          path: output-${{matrix.cfg.output}}.tar
