# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: bazel build -c opt --dynamic_mode=off //...
